### ISSUE TITLE
Spotify Connect Check if active?

### ISSUE THREAD

**Issue by noaboa97** [twonky4/ioBroker.spotify-premium#42]
Hi, so I was wondering if this adapter also let‘s me check if spotify connect is active so I can turn on other devices if it‘s active?

Thanks in advance

**Comment by twonky4** [comment]
Can you give me an example what you mean with "spotify connect is active"? "spotify connect" is the Spotify API, it is always active.

**Comment by noaboa97** [comment]
I would like to check if the playstation is playing music or the api is connecting to it so I can then start the soundsystem to listen to music.

Also I've been checking out the adapter and using it. It's great with a few minor annoyences. 

1. it spams my log with "no playback content" more than once a second.
2. sometimes under the tab objects it opens up all folder of the spotify and it does stuff i guess it's updating the playlists or so and the webinterface kindoff crashes/freezes so i've set in the config to not update playlist since then I didn't experience this problem anymore.

otherwise it's awesome! Thank you for your work

**Comment by twonky4** [comment]
You can check with`spotify-premium.0.devices.YourPlaystation.isAvailable` if it is your device is ready to play music.
And you can check with `spotify-premium.0.devices.YourPlaystation.isActive` (true if the device is currently playing) and `spotify-premium.0.player.isPlaying`.

The other 2 issues are already fixed in version 1.1.0
